
<div class="p-6">
    
    <div class="flex items-center justify-between mb-6 pb-4 border-b border-slate-100">
        <div>
            <h2 class="text-lg font-bold text-[#1B1464]">Invoice</h2>
            <p class="text-[10px] text-slate-400 mt-0.5">#INV-{{ str_pad($booking->id, 6, '0', STR_PAD_LEFT) }}</p>
        </div>
        <div class="w-10 h-10 rounded-xl bg-gradient-to-br from-[#1B1464] to-[#640D5F] flex items-center justify-center">
            <i data-lucide="receipt" class="w-5 h-5 text-white"></i>
        </div>
    </div>

    
    <div class="grid grid-cols-2 gap-5 mb-5">
        <div class="bg-slate-50 rounded-xl p-4">
            <p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2">Buyer</p>
            <p class="text-sm font-bold text-slate-800">{{ $booking->user->name }}</p>
            <p class="text-[11px] text-slate-500 mt-0.5">{{ $booking->user->email }}</p>
        </div>
        <div class="bg-slate-50 rounded-xl p-4">
            <p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2">Event</p>
            <p class="text-sm font-bold text-slate-800">{{ $booking->event->title }}</p>
            <p class="text-[11px] text-slate-500 mt-0.5 flex items-center gap-1">
                <i data-lucide="calendar" class="w-3 h-3"></i>
                {{ date('d M Y', strtotime($booking->event->date)) }}
            </p>
        </div>
    </div>

    
    <div class="bg-slate-50 rounded-xl p-4 mb-5">
        <p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-3">Booking Details</p>
        <div class="space-y-2">
            <div class="flex justify-between text-sm">
                <span class="text-slate-500">Quantity</span>
                <span class="font-semibold text-slate-800">{{ $booking->quantity }} ticket(s)</span>
            </div>
            <div class="flex justify-between text-sm">
                <span class="text-slate-500">Payment Method</span>
                <span class="font-semibold text-slate-800">{{ ucwords(str_replace('_', ' ', $booking->payment_method)) }}</span>
            </div>
            @if($booking->sender_account_name)
            <div class="flex justify-between text-sm">
                <span class="text-slate-500">Sender Account</span>
                <span class="font-semibold text-slate-800">{{ $booking->sender_account_name }}</span>
            </div>
            @endif
            @if($booking->sender_bank)
            <div class="flex justify-between text-sm">
                <span class="text-slate-500">Sender Bank</span>
                <span class="font-semibold text-slate-800">{{ $booking->sender_bank }}</span>
            </div>
            @endif
            <div class="flex justify-between text-sm">
                <span class="text-slate-500">Status</span>
                <span class="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-bold
                    @if($booking->status === 'confirmed') bg-emerald-50 text-emerald-600 border border-emerald-200
                    @elseif($booking->status === 'pending') bg-amber-50 text-amber-600 border border-amber-200
                    @else bg-rose-50 text-rose-600 border border-rose-200
                    @endif">
                    {{ ucwords($booking->status) }}
                </span>
            </div>
            <div class="h-px bg-slate-200 my-1"></div>
            <div class="flex justify-between text-sm">
                <span class="font-bold text-slate-800">Total</span>
                <span class="font-bold text-[#640D5F] text-base">
                    @if($booking->total_price > 0)
                        Rp{{ number_format($booking->total_price, 0, ',', '.') }}
                    @else
                        Free
                    @endif
                </span>
            </div>
        </div>
    </div>

    
    @if($booking->payment_proof_path)
    <div class="bg-slate-50 rounded-xl p-4 mb-5">
        <p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-3">Payment Proof</p>
        <a href="{{ asset('storage/' . $booking->payment_proof_path) }}" target="_blank">
            <img src="{{ asset('storage/' . $booking->payment_proof_path) }}" alt="Payment Proof" class="w-full max-h-48 object-contain rounded-lg border border-slate-200 hover:opacity-90 transition">
        </a>
    </div>
    @endif

    
    <div class="flex items-center justify-between pt-4 border-t border-slate-100">
        <p class="text-[9px] text-slate-400">Generated by Tixtoria</p>
        <button @click="showInvoice = false" class="px-5 py-2 bg-gradient-to-r from-[#1B1464] to-[#640D5F] text-white text-xs font-bold rounded-xl hover:brightness-110 transition">
            Close
        </button>
    </div>
</div>
